### ISSUE TITLE
us01: Como usuario cliente, tengo que registrarme para poder solicitar un servicio

### ISSUE THREAD

**Issue by etomedina** [etomedina/ReparaHub-web-front-end#2]
- [x]  Elaborar el mock-up de la interfaz de registro para un usuario cliente
- [x] Formulario con inputs para el correo y la contraseña
- [x] Controlar inputs y enviar solicitud al backend '/registro-usuario' metodo 'POST'

``{email: string, // "tulio@gmail.com", password: string, // "SoyTul242" } ``

- [ ] Recibir la respuesta de la solicitud, en caso de ser:

- 400, mostraemos alerta con mensaje del backend

- 201, redirigimos al usuario al login

**Comment by etomedina** [comment]
- [ ]  Elaborar el mock-up de la interfaz de registro para un usuario cliente
- [ ] Formulario con inputs para el correo y la contraseña
- [ ] Controlar inputs y enviar solicitud al backend '/registro-usuario' metodo 'POST'

``{email: string, // "tulio@gmail.com", password: string, // "SoyTul242" }

- [ ] Recibir la respuesta de la solicitud, en caso de ser:

- 400, mostraemos alerta con mensaje del backend

- 201, redirigimos al usuario al login

**Comment by etomedina** [comment]
### Criterios de aceptacion

- [ ] Puedo registrar un usuario con email y contraseña
- [ ] No puedo registrar un usuario con una contraseña invalida, es decir que tenga menos de 10 caracteres
- [ ] No puede existir dos usuarios con el mismo correo.

**Comment by cjrj** [comment]
![001 - registro](https://user-images.githubusercontent.com/94300513/159376535-02c48512-6e46-4490-9f5c-4665671853fb.jpg)

**Comment by etomedina** [comment]
### Feedback @cjrj 
1) Incluir alternativas de ingreso, google, twitter o fb (Averiguar si son pagas o no)
2) Tipografia atento (que no sean dos distintas en una visual)
3) Diseño bajo modalidad mobile-first

**Comment by etomedina** [comment]
Chicos, recuerden pensar la totalidad de paginas que el usuario vera:
-Login (Falta)
-Sign up (Carlos)
*
- Pantalla principal (usuario-cliente)
*Settings (Modificar contrase;a, vehiculo asociado, incluir vehiculo adicional)
*Boton con coordenadas de ubicacion del incidente
*Formulario (Tipos de fallas generales o agregar si no aparece)

- Pantalla principal (usuario-proveedor)
*Estilo de correo, donde llegan todas las incidencias

**Comment by cjrj** [comment]
Hola muchachos. Les envio el enlace para que vean los Blueprints.
Me falta la parte del lado del proveedor de servicio.


[https://www.figma.com/file/iZm95hgWORZ5bsTrUZGV7J/Untitled?node-id=0%3A1](url)
